services:

 database:
  container_name: sql-server-db
  image: mcr.microsoft.com/mssql/server:2019-latest
  ports:
   - "5533:1433"
  environment:
   SA_PASSWORD: "Admin123!"
   ACCEPT_EULA: "Y"
  volumes:
   - kyc-saga-sqldb:/var/opt/mssql

 mongodb:
  container_name: mongodb
  image: mongo:6.0
  volumes:
   - ~/mongo:/data/db
  ports:
   - "27017:27017"

volumes:
 kyc-saga-sqldb: