services:

 database:
  container_name: sql-server-db
  image: mcr.microsoft.com/mssql/server:2019-latest
  ports:
   - "5533:1433"
  environment:
   SA_PASSWORD: "Admin123!"
   ACCEPT_EULA: "Y"
  volumes:
   - kyc-saga-sqldb:/var/opt/mssql

 mongodb:
  container_name: mongodb
  image: mongo:6.0
  volumes:
   - ~/mongo:/data/db
  ports:
   - "27017:27017"


 eventsapi:
  image: events
  build: 
   context: ./backend
   dockerfile: ./Services/Events/API/Dockerfile
  ports:
   - 7203:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 notificationsapi:
  image: notification
  build: 
   context: ./backend
   dockerfile: ./Services/Notification/Notification.API/Dockerfile
  ports:
   - 7205:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 subscriptionsapi:
  image: subscriptions
  build: 
   context: ./backend
   dockerfile: ./Services/Subscription/Subscription.API/Dockerfile
  ports:
   - 7204:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 web:
  build: 
   context: ./frontend
   dockerfile: ./Dockerfile
  ports:
   - 3000:3000
  environment:
   NODE_ENV: "Docker"

volumes:
 kyc-saga-sqldb: