ALTER TABLE algorithms.company
ADD COLUMN audit_dtime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN audit_author VARCHAR(255) NOT NULL DEFAULT 'system',
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE algorithms.person
ADD COLUMN audit_dtime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN audit_author VARCHAR(255) NOT NULL DEFAULT 'system',
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid();
