name: mweb_environment

networks:
 mweb-develop:
  driver: bridge

services:
 database:
  container_name: sql-server-db
  image: mcr.microsoft.com/mssql/server:2019-latest
  ports:
   - "5533:1433"
  environment:
   SA_PASSWORD: "Admin123!"
   ACCEPT_EULA: "Y"
  volumes:
   - kyc-saga-sqldb:/var/opt/mssql

 mongodb:
  container_name: mongodb
  image: mongo:latest
  volumes:
   - ~/mongo:/data/db
  ports:
   - "27017:27017"

 mweb-keycloak:
  container_name: mweb-keycloak
  image: quay.io/keycloak/keycloak:latest
  user: root
  ports:
   - 8036:8080
  networks:
   - mweb-develop
  environment:
   KEYCLOAK_ADMIN: admin
   KEYCLOAK_ADMIN_PASSWORD: admin
  deploy:
   resources:
    limits:
     memory: 512M
  healthcheck:
   # This creates a basic java file app that pings /health/live and checks wether the response is 200 or not.
   test: '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/health/live'
   interval: 5s
   timeout: 5s
   retries: 10
  command:
   start-dev
   
 mweb_logs_seq:
  image: datalust/seq
  container_name: mweb_logs_seq
  ports:
   - 5341:80
  environment:
   ACCEPT_EULA: Y
  networks:
   - mweb-develop
  mem_limit: 128M
  
 mweb_postgres:
  image: postgres:latest
  container_name: mweb_postgres
  ports:
   - 5432:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: password
  networks:
   - mweb-develop
  mem_limit: 256M
  
 rabbit:
  image: rabbitmq
  container_name: mweb_rabbit
  ports:
   - 5672:5672
   - 15672:15672
  hostname: localhost
  environment:
   RABBITMQ_DEFAULT_USER: guest
   RABBITMQ_DEFAULT_PASS: guest
  networks:
   - mweb-develop
  mem_limit: 256M

volumes:
 kyc-saga-sqldb: