name: mweb_application

services:

 gateway:
  image: gateway
  build: 
   context: ../../backend
   dockerfile: ./Gateways/Gateway.Web/Dockerfile
  ports:
   - 7201:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 identityapi:
  image: identity
  build: 
   context: ../../backend
   dockerfile: ./Services/Identity/Identity.API/Dockerfile
  ports:
   - 7202:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 eventsapi:
  image: events
  build: 
   context: ../../backend
   dockerfile: ./Services/Events/Events.API/Dockerfile
  ports:
   - 7203:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 notificationsapi:
  image: notification
  build: 
   context: ../../backend
   dockerfile: ./Services/Notification/Notification.API/Dockerfile
  ports:
   - 7205:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 subscriptionsapi:
  image: subscriptions
  build: 
   context: ../../backend
   dockerfile: ./Services/Subscription/Subscription.API/Dockerfile
  ports:
   - 7204:80
  environment:
   ASPNETCORE_ENVIRONMENT: "Docker"
   ASPNETCORE_URLS: "http://+:80"

 web:
  build: 
   context: ../../frontend
   dockerfile: ./Dockerfile
  ports:
   - 3000:3000
  environment:
   NODE_ENV: "Docker"